#!/usr/bin/env bash
# script that loop from 1 to 10
# displays bad luck for the 4th iteration
# displays good luck for the 8th iteration
# displays Best School for other iteration

j=0
while [ $j -lt "10" ]
do
	if [ $j -eq "3" ]
	then
		echo "bad luck"
	elif [ $j -eq "7" ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(("j = j + 1"))
done
