#!/usr/bin/env bash
# script that give you information about the school file
fd="school"
if [ -a $fd ]
then
	echo "school file exists"
	if ! [[ -s $fd ]]
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if [ -f $fd ]
	then
		echo "school file is a regular file"
	fi
else
	echo "school file does not exists"
fi
